name: fave_reads
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  postgres: ^1.0.2

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0